# Generated by Django 5.0.2 on 2025-04-07 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='address',
        ),
    ]
